package:
  name: pyhessio
  version: 0.3.0

source:
  git_url: https://github.com/cta-observatory/pyhessio
  git_branch: rpath_macos

build:
  number: 1
  binary_relocation: True
  detect_binary_files_with_prefix: True
